# TO-DO: BigQuery Connectivity


*   ~~Shift description columns to a completely different dataframe (e.g., company_id, description)~~ (Now "company_description_df")
*   ~~Create csv files from dataframes with dropped descriptions~~
*   ~~Upload new csv files to BigQuery~~
*   Establish conneciton between BigQuery selects and Python statements

# TO-DO: Data Preprocessing


*   Check employee_counts.csv "time_recorded" column to ensure the maximum recorded time has been selected for every unique company_id. (i.e., Make sure the most updated employee count has been captured for each unique company.)

#Importing Primary Libraries

In [1]:
# Import statements
import pandas as pd

#Importing Data

In [2]:
# Importing dataset from kaggle
import kagglehub

# Download latest version
path = kagglehub.dataset_download("arshkon/linkedin-job-postings")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/arshkon/linkedin-job-postings/13.archive...

100%|██████████| 159M/159M [00:01<00:00, 164MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/arshkon/linkedin-job-postings/versions/13

#Data Accessibility Tests

In [3]:
# Creating an ancillary paths dictionary for the dataset
ancillary_directories = ['companies', 'jobs', 'mappings']
job_posts_path_dict = {}

for directories in ancillary_directories:
  job_posts_path_dict[directories] = path + '/' + directories

In [4]:
# Grabbing the filename of the job postings data
job_posts_filename = path + '/' + 'postings.csv'

In [5]:
# Creating a pandas dataframe from 'postings.csv'
job_posts_df = pd.read_csv(job_posts_filename)

In [6]:
# TODO - Convert these dataframes into dictionaries (e.g., companies_dict{...}, jobs_dict{...}, etc.)

# Creating pandas dataframes for the ancillary directories
companies_df = pd.read_csv(job_posts_path_dict[ancillary_directories[0]] + '/companies.csv')
companies_industries_df = pd.read_csv(job_posts_path_dict[ancillary_directories[0]] + '/company_industries.csv')
companies_specialities_df = pd.read_csv(job_posts_path_dict[ancillary_directories[0]] + '/company_specialities.csv')
companies_employee_counts_df = pd.read_csv(job_posts_path_dict[ancillary_directories[0]] + '/employee_counts.csv')

#jobs_df = TODO - Jobs has several sub files
jobs_benefits_df = pd.read_csv(job_posts_path_dict[ancillary_directories[1]] + '/benefits.csv')
jobs_industries_df = pd.read_csv(job_posts_path_dict[ancillary_directories[1]] + '/job_industries.csv')
jobs_skills_df = pd.read_csv(job_posts_path_dict[ancillary_directories[1]] + '/job_skills.csv')
jobs_salaries_df = pd.read_csv(job_posts_path_dict[ancillary_directories[1]] + '/salaries.csv')

#mappings_df = TODO - Mappings has sub files
mappings_industries_df = pd.read_csv(job_posts_path_dict[ancillary_directories[2]] + '/industries.csv')
mappings_skills_df = pd.read_csv(job_posts_path_dict[ancillary_directories[2]] + '/skills.csv')

ancillary_datasets_list = [
    companies_df,
    companies_industries_df,
    companies_specialities_df,
    companies_employee_counts_df,
    jobs_benefits_df,
    jobs_industries_df,
    jobs_skills_df,
    jobs_salaries_df,
    mappings_industries_df,
    mappings_skills_df
]

# Creating Description Dataframe from Company Info

In [41]:
# At some point, we may need to be very careful about maintaining our job posting IDs.
company_description_df = ancillary_datasets_list[0][['company_id', 'description']].copy()

In [42]:
company_description_df.head()

   company_id                                        description
0        1009  At IBM, we do more than work. We create. We cr...
1        1016  Every day millions of people feel the impact o...
2        1025  Official LinkedIn of Hewlett Packard Enterpris...
3        1028  We’re a cloud technology company that provides...
4        1033  Accenture is a leading global professional ser...

In [ ]:
ancillary_datasets_list[0].drop(["description"], axis=1, inplace=True)

In [52]:
# Dropping "address" (i.e., the street address) column of the company dataset as city, country, and zip code should be good enough
ancillary_datasets_list[0].drop(["address"], axis=1, inplace=True)

# CURRENT FILTERS: description, address

# Dataset Inspector

In [60]:
# Select dataset to inspect...
# 0 - companies/companies.csv
# 1 - companies/company_industries.csv
# 2 - companies/company_specialities.csv
# 3 - companies/employee_counts.csv
# ...
# 8 - mappings/industries.csv
# 9 - mappings/skills.csv

DATASET_INDEX = 2

current_dataset = ancillary_datasets_list[DATASET_INDEX]

In [61]:
# View information about current dataset
current_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169387 entries, 0 to 169386
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   company_id  169387 non-null  int64
 1   speciality  169387 non-null  object
dtypes: int64(1), object(1)
memory usage: 2.6+ MB

In [62]:
# View first five rows of current dataset
current_dataset.head(10)

   company_id              speciality
0    22292832      window replacement
1    22292832  patio door replacement
2       20300      Commercial Banking
3       20300          Retail Banking
4       20300                Mortgage
5       20300         Private Banking
6       20300          Trust Services
7       20300               Insurance
8       20300       Wealth Management
9     3570660             Advertising

In [56]:
current_dataset.to_csv('filtered_companies.csv', index=False)